spring.application.name=frontend
server.port=8080
management.endpoints.web.exposure.include=*
logging.level.dev.snbv2.cloudcart=INFO

endpoint.catalog=http://catalog:8080
endpoint.orders=http://orders:8080
endpoint.payments=http://payments:8080
endpoint.order-history=http://order-history:8080
