spring.application.name=orderhistory
server.port=8080
spring.rabbitmq.host=${RABBITMQ_HOST:rabbitmq}
logging.level.dev.snbv2.cloudcart=INFO
management.endpoints.web.exposure.include=*
spring.jpa.hibernate.ddl-auto=create-drop
